project:
  type: website
  output-dir: docs

website:
  title: "Mentorship Training and Orientation"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/yabellini/ropensci-mentors
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: instructor_notes.qmd
        text: Instructor Notes

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

